#!/usr/bin/env bash
set -euo pipefail

base_ref=$(git symbolic-ref --short refs/remotes/origin/HEAD)
merge_base=$(git merge-base HEAD "$base_ref")

files=$(git diff --name-only "$merge_base" HEAD)

kt_files=$(echo "$files" | grep -E '\.(kt|kts)$' || true)
if [[ -n $kt_files ]]; then
  echo "$kt_files" | xargs ktlint
fi

md_files=$(echo "$files" | grep -E '\.(md|mdx)$' || true)
if [[ -n $md_files ]]; then
  echo "$md_files" | xargs prettier -c
fi
